### ISSUE TITLE
Criar uma página com uma tabela dentro

### ISSUE THREAD

**Issue by brunojose1977** [brunojose1977/codigo-secreto#1]
O projeto tem a necessidade da criação de uma página em HTML que contenha uma tabela dentro.

**Sugestão de colunas**

[ Nome ]  [ idade ]

**Comment by lucascostadummy** [comment]
Iniciando o atendimento da Issue

**Comment by lucascostadummy** [comment]
Issue finalizada no commit #7  pelo @lucascostadummy
